# Előszó {.unnumbered}

Ez a könyv a Neumann János Egyetem és az MNB Intézet által indított Nemzetközi Gazdaság és Gazdálkodás mesterszakának *Kvantitatív alapok* nevű tantárgyához készült. Célom a hallgatók felkészülését segíteni azzal, hogy egy helyen, átlátható formában közlöm a tantárgyhoz készült jegyzeteket, példákat, gyakorlatokat és ábrákat. A Kvantitatív alapok tantárgy felépítésénél akárcsak ezen könyv megírásánál nagyban merítettem Russ Poldrack Statistical Thinking for the 21st Century című munkájából, Nagy Tamás Adatelemzés és statisztikai következtetés nevű órai jegyzeteiből és Andy Field statisztika tankönyveiből. Ha az olvasó ezen művekből ismerős gondolatokat, példákat vagy magyarázatokat lát, akkor azok nagy valószínűséggel onnan is lettek átvéve. Én magam is nagyrészt tőlük tanultam azt, amit a kvantitatív elemzésről tudok. Ez a három ember nálam sokkal többet gondolkozott azon, hogyan kell hatékony módon statisztikát tanítani egyetemista hallgatóknak, így nem láttam értelmét, hogy a tantárgy felépítését a nulláról kezdjem. Ezúton is szeretném megköszönni a segítségük!

# Köszönetnyílvánítás

Szeretnék továbbá köszönetet mondani Ignits Györgyinek, Kapitány Balázsnak, Szászi Barnabásnak és Szécsi Péternek, akik példa adatok megosztásán keresztül segítették a könyv létrejöttét.

A KÖNYVÖN MOST IS AKTÍVAN DOLGOZOM, EZ NEM A VÉGLEGES VÁLTOZAT!
