# Tudományos módszer

## A tudomány célja

-   A tudomány célja, hogy általános magyarázotokkal szolgáljon a minket körülvevő világról

-   A tudományos magyarázatok leegyszerüsített formában **írják le** a valóságot

-   A tudományos magyarázatok segítségével így képesek vagyunk

    -   jól informált **döntéseket** hozni

    -   **predikciókat** alkotni új helyzetekre a már meglévő tudásunk alapján

-   Később majd látni fogjuk, hogy a kutatási folyamat sok pontján félrecsúszhat az, hogy a kutatásunk alapján megbízható döntéseket hozzunk vagy predikciókat alkossunk

-   A tudományos megközelítés azonban nem az egyetlen mód, amelyen keresztül a valóságot magyarázzuk

-   Miben más, mint egyéb megismerési módok?

    -   Pl: vallás: autoritás alapú

    -   Kritikai megközelítés

    -   Tesztelhető (falszifikálható hipotézisek

## Az empirikus tudományos folyamat lépései

1.  Általános kérdésfelvetés

    -   Ez talán a legegyszerűbb lépés, az ember kíváncsi természetű, szeretné érteni az őt körülvevő valóságot

2.  Elmélet alkotás

    -   Ahhoz, hogy egy kérdést meg tudjunk válaszolni empirikus módon egy elméletet kell alkotnunk a kérdés mögött álló lehetséges hatásmechanizmusról

    -   Az elmélet falszifikálható kell legyen

        -   Tudunk olyan megfigyeléseket tenni amelyek fényében az elméletet elvetjük

    -   A jó elméletek

        -   Elérés (reach): minél több jelenséget magyaráz meg egy elmélet annál jobb

        -   Parszimónia: két versenyző elmélet közül az a jobb, ami kevesebb elemből áll

            -   Lásd Occam borotvája

        -   Konzervatívizmus: Mennyire illeszkedik már meglévő tesztelt és elfogadott elméletekhez

3.  Hipotézis alkotás

    -   A hipotézis az elméletünknek egy konkrétan tesztelhető operacionalizált része

    -   Egy elmélet alapján többféle hipotézist fel lehet állítani

    -   A hipotézis alapján predikciókat alkotunk, amelyeket tesztelünk

    -   Egy hipotézis bizonyításával nem bizonyítjuk az elméletet is!

    -   De tudjuk a teszt eredményei által tovább finomítani az elméletet

    -   Vagy elvetjük azt

    -   Fontos, hogy a hipotézis valóban illeszkedjen az adott elmélethez

4.  Kutatási elrendezés

    -   A hipotézis tesztelésére annak feltételezései alapján egy kutatást tervezünk

    -   A kutatás megtervezésénél számos különböző módszertan közül tudunk választani

    -   Mindegyiknek vannak előnyei és hátránya, a hipotézis és az elérhető erőforrások fényében választunk közülük

        -   Kérdőíves

        -   Megfigyeléses

        -   Kísérleti

    -   Van pár általános szempont, amelyeket módszertantól függetlenül figyelembe kell vennünk és amelyek befolyásolják az eredményekből levontható következtetéseket

        -   Minta felépítése és mintaméret

        -   Mérőeszköz és annak pontossága, megbízhatósága, és granularitása

    -   Ahhoz hogy oksági viszonyt feltételezzünk két jelenség közt nem feletkezhetünk meg az adatgyűjtés módjáról

    -   Megfigyeléses vizsgálatoknál nem tudjuk biztosan kijelenteni hogy két változó között oksági viszony van

        -   Lehetséges hogy egyébb faktorok befolyásolják a kapott együttjárást

        -   <https://www.tylervigen.com/spurious-correlations>

    -   Ezért a kutatók általában az oksági viszony meghatározásához kísérleti kutatási elrendezést használnak (pl: randomized control trial)

        -   A lehetséges, de nem viszgált befolyásoló faktorokat random mintavételezés útján zárják ki az adatgyűjtés során

    -   Vannak statisztikai módszerek amivel utólag is kontrollálni tudjuk ezeket a változókat, de sokkal nehezebb ezt utólag megtenni

    -   Ez is kiemeli a jól megtervezett kutatások és részletesen kidolgozott elméletek fontosságát!

    -   Mintavételezés

        -   Az esetek kis részében tudjuk az egész populációt vizsgálni

        -   Minták tesztelésén keresztül vonunk le általános következtetéseket

        -   De mekkora mintára van szükség ahhoz, hogy a populációra tudjunk következtetni?

5.  Adatok feldolgozása

    -   Általában nem szokták külön lépésként kezelni, de az óra témaja és az eredményekre gyakorolt lehetséges hatása miatt fontos megemlíteni

    -   A kapott adatokat befolyásolja az általunk választott kutatási elrendezés és az adatgyűjtés során fellépő váratlan torzító tényezők

    -   Nagyon ritka esetben készek az adatgyűjtés után az adatok az elemzésre

    -   Általában először adat rendezést és adattisztítást kell elvégeznünk

6.  Statisztikai elemzés

    -   Az elemzés során használhatunk

        -   Leíró statisztikai eljárásokat

        -   Következtetéses statisztikai eljárásokat

    -   Rengeteg statisztikai eljárás van, a statisztikusok most is dolgoznak újak kifejlesztésén és validációján

    -   Az, hogy milyen eljárást választunk függ a hipotézisünktől, a kutatási elrendezésünktől, és az adatgyűjtés során kapott adatoktól

    -   Többféle lehetséges valid elemzési út is létezik

        -   Lást: multi-analyst study

7.  Eredmények értelmezése

    -   A statisztikai elemzés eredményeinek értelmezésére a tudományos folyamat összes eddigi lépése kihat

    -   Kutatóként szeretnénk egyértelmű válaszokat kapni az általunk feltett kérdésekre

        -   Sajnos nagyon kevés esetben ez a helyzet

        -   Ez részben a tudományos folyamat összetettségének az eredménye

        -   Részben ennek a vágynak is szerepe van a p-értékek abuzálásában

        -   Egy kutatásból nagyon ritkán kapunk egyértelmű válaszokat

            -   Lásd: metaanalízis, szisztematikus összefoglaló (systematic review)

    -   Pár példa helyzet arra, amikor a tudományos módszer összetettsége árnyalja a statisztikai elemzés eredményeinek értelmezését:

        -   A választott mérőeszközök valójában nem a vizsgált konstruktumot mérik

        -   A minta milyensége vagy mérete nem indokolja az eredmények általánosítását

        -   Az adattisztítás során olyan megfigyelések is bent maradtak, amelyek szisztematikusan torzítják az eredményeket

    -   Az értelmezést korlázotó tényezőkről általában a tudományos publikáció limitációk szakaszában számolunk be

## A statisztika szerepe a tudományban

-   A komplex valóság egyszerüsített leírása, ami egyúttal azt is elmondja mennyire lehetünk bizonytalanok ebben a tudásban

-   Miért van szükség a statisztikára?

    -   Heurisztikák veszélye

        -   Példa: USA bűnelkövetések gyakorisága

            -   Sokkal gyakoribbnak gondoljuk a bűnelkövetések számát, mint amilyen gyakoriak a valóságban

            -   Elérhetőségi torzítás (kognitív torzítás egyik fajtája)

            -   Média szerepe?

    -   Statisztika segít abban hogy tanuljunk az adatokból

        -   Hogyan frissítsük előzetes tudásunk az új adatok fényében

-   A statisztika az adatösszesítésről szól

    -   Hogyan tudunk úgy leegyszerüsíteni befogadhatatlan mennyiségű megfigyelést, hogy azok segítségével hipotézisünk tesztelni tudjuk, de fontos információ ne vesszen el

-   A statisztika a bizonytalanság kezeléséről szól

    -   A világ összetett

    -   A legtöbb összetett jelenséget nehéz determinisztikus módon megmagyarázni

    -   Bár tudunk ok-okozati kapcsolatot felállítani bizonyos összefüggések között általában ezek nem determinisztikus, hanem probabilisztikus predikciókhoz vezetnek

        -   Lásd: dohányzás és tüdőrák
            -   Tudjuk, hogy a dohányzás növeli a tüdőrák esélyét, azonban nem lehet biztosra mondani, hogyha valaki dohányzik, akkor mindenképp tüdőrákos is lesz

    -   A statisztika nem tud bizonyítani (úgy ahogy a matematika tud)

        -   Hanem evidenciát tud felmutatni egy hipotézis mellett az eddigi megfigyelések fényében, de a bizonytalanságot nem tudjuk nullára csökkenteni

A statisztika a kompromisszomkról szól

-   Nincs egyetlen objektív módszer a statisztikában

-   Mindig a vizsgált kérdés, az adatgyűjtést és elemzést korlátozó tényezők függvényében kell megtalálnunk a legmeggyőzőbb elemzési utat

    -   Ahhoz, hogy a választott elemzési út ténylegesen meggyőző legyen transzparensen közölnünk kell analitikus döntéséinket és a mellette szóló érveket

    -   Ez az alapfeltétele az analitikus megismételhetőségnek: más kutató ugyanazokat az adatokat vizsgálva megegyező analatikus úton ugyanarra az eredményre érkezik

        -   Ez sajnos ma a tudományban nem magától értetődő!

-   Több valid elemzési út is lehet ugyanannak a kérdésnek a vizsgálatára

    -   A szakmai közösség feladata ezeknek a felülbírálata

    -   Lásd: multi analyst kutatások

-   A tudomány iteratív módon lépésenként épül fel

    -   Lehetséges, hogy a ma még megbízhatónak számító elemzési utat új eredmények fényében elvetjük

    -   És ezzel nincs baj!
